api/urls.py
from django.urls.conf import path
from . import views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

urlpatterns = [
    path('users/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('users/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

    path('', views.getRoutes),
    path('projects/', views.getProjects),
    path('projects/<str:pk>/', views.getProject),
    path('projects/<str:pk>/vote/', views.ProjectVote),
    path('remove-tag/', views.removeTag),
]

devsearch/urls.py
from django.contrib import admin

from django.urls.conf import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('projects/', include('projects.urls')),
    path('api/', include('api.urls')),

    path('reset_password/', auth_views.PasswordResetView.as_view(template_name='reset_password.html'), name='reset_password'),
    path('reset_password_sent/', auth_views.PasswordResetDoneView.as_view(template_name='reset_password_sent.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='reset.html'), name='password_reset_confirm'),
    path('reset_password_complete/', auth_views.PasswordResetCompleteView.as_view(template_name='reset_password_complete.html'), name='password_reset_complete'),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path

from . import views

urlpatterns = [

    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name='register'),


    path('', views.profiles, name='profiles'),
    path('profile/<str:pk>/', views.userProfile, name='user-profile'),
    path('account/', views.userAccount, name='account'),
    
    path('edit-account/', views.editAccount, name='edit-account'),

    path('skills/', views.addSkills, name='skills'),
    path('update-skills/<str:pk>/', views.updateSkills, name='update-skills'),
    path('delete-skills/<str:pk>/', views.deleteSkills, name='delete-skills'),

    
    path('inbox/', views.inbox, name='inbox'),
    path('message/<str:pk>/', views.message, name='message'),
    path('create-message/<str:pk>/', views.createMessage, name = 'create-message')
]

projects/models.py
from django.db import models
import uuid

from users.models import Profiles


class Project(models.Model):
    owner = models.ForeignKey(Profiles, on_delete=models.CASCADE, null=True, blank=True)
    title = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    featured_image = models.ImageField(null=True, blank=True, default='default.jpg', upload_to='projects_pic')
    demo_link = models.CharField(max_length=2000, null=True, blank=True)
    source_link = models.CharField(max_length=2000, null=True, blank=True)
    tags = models.ManyToManyField('Tag', blank=True)
    create= models.DateTimeField(auto_now_add=True)
    vote_total = models.IntegerField(default=0, null=True, blank=True)
    vote_ratio = models.IntegerField(default=0, null=True, blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)


    def __str__(self):
        return self.title
    
    class Meta:
        ordering = ['-vote_ratio', '-vote_total', 'title']
    @property 
    def imageURL(self):
        try:
            url = self.featured_image.url
        except:
            url =''
        return url


    @property
    def reviewers(self):
        queryset = self.review_set.all().values_list('owner__id', flat=True)
        return queryset
    
    @property
    def getVoteCount(self):

        reviews = self.review_set.all()
        upVotes = reviews.filter(value='up').count()
        totalVotes = reviews.count()

        ratio = (upVotes / totalVotes) * 100
        self.vote_total = totalVotes
        self.vote_ratio = ratio

        self.save()



# reviews
class Review(models.Model):
    VOTE_TYPE = (
        ('up', 'Up Vote'),
        ('down', 'Down Vote'),
    )

    owner = models.ForeignKey(Profiles, on_delete=models.CASCADE, null=True)
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    body = models.TextField(null=True, blank=True)
    value = models.CharField(max_length=200, choices=VOTE_TYPE)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    class Meta:
        unique_together = [['owner', 'project']]

    def __str__(self):
        return self.value

# Tag model

class Tag(models.Model):
    name = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.name

users/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid



# Create your models here.
class Profiles(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=500, null=True, blank=True)
    username = models.CharField(max_length=200, null=True, blank=True)
    location = models.CharField(max_length=200, null=True, blank=True)
    short_intro = models.CharField(max_length=200, null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    profile_image = models.ImageField(null=True, blank=True, upload_to='profiles/', default='user-default.png')

    social_github = models.CharField(max_length=200, null=True, blank=True)
    social_linkedin = models.CharField(max_length=200, null=True, blank=True)
    social_twitter = models.CharField(max_length=200, null=True, blank=True)
    social_youtube = models.CharField(max_length=200, null=True, blank=True)
    social_website = models.CharField(max_length=200, null=True, blank=True)

    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return str(self.username)
    
    class Meta:
        ordering = ['created']



# skills
class Skills(models.Model):

    owner = models.ForeignKey(Profiles, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):

        return self.name



# messages
class Message(models.Model):

    sender = models.ForeignKey(Profiles, on_delete=models.SET_NULL, null=True, blank=True)
    recipient = models.ForeignKey(Profiles, on_delete=models.SET_NULL, null=True, blank=True, related_name='messages')
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(max_length=200, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    body = models.TextField()
    is_read = models.BooleanField(default=False, null=True)
    created = models.DateTimeField(auto_now_add=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)

    def __str__(self):
        return self.subject

    class Meta:
        ordering = ['is_read', '-created']
    

users/views.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .form import CustomUserCreationForm, MessageForm, ProfileForm, SkillsForm
from django.contrib.auth.decorators import login_required
from users.models import Profiles, Skills
from .utils import profilesPaginations, searchProfiles
from .models import Message
# login
def loginUser(request):
    page ='register'
    if request.user.is_authenticated:
        return redirect('profiles')

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'user doe not exist')
        
        # this return the instance of a user if the pass and username are correct. and return None otherwise.
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            messages.error(request, 'You are no logged in')
            return redirect(request.GET.get('next') if 'next' in request.GET else 'account')

        else:
            messages.error(request, 'username or password is not correct')

    return render(request, 'users/login_register.html')


# signup user
def registerUser(request):
    page ='register'
    form = CustomUserCreationForm()
    if request.method =='POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username= user.username.lower()
            user.save()
            messages.success(request, 'Account was created')

            login(request, user)
            return redirect('edit-account')
        else:
            messages.error(request, 'An error occured during registration')


    context ={
        'page':page,
        'form':form,
    }
    return render(request, 'users/login_register.html', context)

# logout
def logoutUser(request):
    logout(request)
    messages.success(request, 'username or password is not correct')
    return redirect('login')


# profiles

def profiles(request):
    profiles, search_query = searchProfiles(request)
    custome_range, profiles = profilesPaginations(request, profiles, 6)
    context = {
        'profiles':profiles,
        'search_query':search_query,
        'custome_range':custome_range,
    }

    return render(request, 'users/profiles.html', context)


def userProfile(request, pk):
    profile = Profiles.objects.get(id=pk)
    topSkills = profile.skills_set.exclude(description__exact="")
    otherSkills = profile.skills_set.filter(description='')
    context ={
        'profile':profile,
        'topSkills':topSkills,
        'otherSkills':otherSkills,
    }

    return render(request, 'users/user-profile.html', context)

# user page
def userAccount(request):
    profile = request.user.profiles
    context ={
        'profile':profile,
    }
    return render(request, 'users/account.html', context)


# edit account
@login_required(login_url='login')
def editAccount(request):
    profile = request.user.profiles
    form = ProfileForm(instance=profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account was updated successfully')
            return redirect('profiles')
    context ={
        'form':form,
    }
    return render(request, 'users/profile_form.html', context)

# skillform view
@login_required(login_url='login')
def addSkills(request):
    form = SkillsForm()
    if request.method == 'POST':
        form = SkillsForm(request.POST)
        if form.is_valid():
            skill = form.save(commit=False)
            skill.owner = request.user.profiles
            skill.save()
            return redirect('account')
    context = {
        'form':form,
    }
    return render(request, 'users/add_skills.html', context)

# update skills 
@login_required(login_url='login')
def updateSkills(request, pk):
    skill = request.user.profiles.skills_set.get(id=pk)
    form = SkillsForm(instance=skill)
    if request.method == 'POST':
        form = SkillsForm(request.POST, instance=skill)
        if form.is_valid():
            # skill = form.save(commit=False)
            # skill.owner = request.user.profiles
            # skill.save()
            form.save()
            return redirect('account')
    context = {
        'form':form,
    }
    return render(request, 'users/add_skills.html', context)

# delete skills
def deleteSkills(request, pk):
    skill = request.user.profiles.skills_set.get(id=pk)
    if request.method == 'POST':
        skill.delete()
        return redirect('account')
    context = {
        'item':skill,
    }
    return render(request, 'delete_project.html', context)


# inbox
@login_required(login_url='login')
def inbox(request):
    profile = request.user.profiles
    msgRequest = profile.messages.all()
    unreadCount = msgRequest.filter(is_read=False).count()

    context = {
        'msgRequest':msgRequest,
        'unreadCount':unreadCount,
    }
    return render(request, 'users/inbox.html', context)

# messages
@login_required(login_url='login')
def message(request, pk):
    
    unreadMsg = request.user.profiles.messages.get(id=pk)
    if unreadMsg.is_read == False:
        unreadMsg.is_read = True
        unreadMsg.save()
        
    context = {
        'unreadMsg':unreadMsg,
    }

    return render(request, 'users/message.html', context)

# create message
def createMessage(request,pk):

    recipient = Profiles.objects.get(id=pk)
    form = MessageForm()

    try:
        sender = request.user.profiles
    except:
        sender = None

    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit=False)
            message.sender = sender
            message.recipient = recipient

            if sender:
                message.name = sender.name
                message.email = sender.email
            message.save()
            messages.success(request, 'Your message was successfully sent')
            return redirect('user-profile', pk=recipient.id)
    context = {
        'recipient':recipient,
        'form':form,
    }
    return render(request, 'users/message_form.html', context)

users/templates/users/account.html
{% extends 'main.html' %}

{% block content %}
<main class="settingsPage profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'edit-account' %}"><i class="im im-edit"></i> Edit</a>
              <img class="avatar avatar--xl dev__avatar" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if profile.social_twitter %}
                
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
            
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
             {{profile.bio}}
            </p>
          </div>
          <div class="settings">
            <h3 class="settings__title">Skills</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'skills' %}"><i class="im im-plus"></i> Add Skill</a>
          </div>

          <table class="settings__table">

            {% for skill in profile.skills_set.all %}
            <tr>
                <td class="settings__tableInfo">
                  <h4>{{skill.name}}</h4>
                  <p>
                   {{skill.description}}
                  </p>
                </td>
                <td class="settings__tableActions">
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-skills' skill.id %}"><i class="im im-edit"></i> Edit</a>
                  <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-skills' skill.id %}?next=/account/"><i class="im im-x-mark-circle-o"></i>
                    Delete</a>
                </td>
              </tr>
            {% endfor %}
            
          </table>

          <div class="settings">
            <h3 class="settings__title">Projects</h3>
            <a class="tag tag--pill tag--sub settings__btn tag--lg" href="{% url 'create-project' %}"><i class="im im-plus"></i> Add Project</a>
          </div>

          <table class="settings__table">

           {% for project in profile.project_set.all %}
           <tr>
            <td class="settings__thumbnail">
              <a href="{% url 'project' project.id %}"><img src="{{project.featured_image.url}}" alt="Project Thumbnail" /></a>
            </td>
            <td class="settings__tableInfo">
              <a href="{% url 'project' project.id %}">{{project.title}}</a>
              <p>
               {{project.description|slice:'50'}}
              </p>
            </td>
            <td class="settings__tableActions">
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'update-project' project.id %}"><i class="im im-edit"></i> Edit</a>
              <a class="tag tag--pill tag--main settings__btn" href="{% url 'delete-project' project.id %}?next=/account/"><i class="im im-x-mark-circle-o"></i>
                Delete</a>
            </td>
          </tr>
       
           {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/users/add_skills.html
{% extends 'main.html' %}

{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" method="POST">
                {% csrf_token %}
                <!-- Input:Text -->
                {% for field in form %}
                <div class="form__field">
                    <label for="formInput#text">{{field.label}}: </label>
                  {{field}}
                </div>
                {% endfor %}
              
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/inbox.html
{% extends 'main.html' %}

{% block content %}
<main class="inbox my-xl">
    <div class="content-box">
      <h3 class="inbox__title">New Messages(<span>{{unreadCount}}</span>)</h3>
      <ul class="messages">
        
      {% for message in msgRequest %}
        
        {% if message.is_read == False %}
        <li class="message message--unread">
          
          {% else %}
          
          <li class="message">
          {% endif %}
          <a href="{% url 'message' message.id %}">
            <span class="message__author">{{message.name}}</span>
            <span class="message__subject">{{message.subject}}</span>
            <span class="message__date">{{message.created}}</span>
          </a>
        </li>
        {% endfor %}

      </ul>
    </div>
  </main>
{% endblock %}

users/templates/users/login_register.html
{% extends 'main.html' %}
{% load static %}
{% block content %}


{% if page == 'register' %}

<!-- sign up -->
<div class="auth">
  <div class="card">
    <div class="auth__header text-center">
      <a href="/">
        <img src="{% static 'images/icon.svg' %}" alt="icon" />
      </a>
      <h3>Account SignUp</h3>
      <p>Create a new developer account</p>
    </div>

    <form action="{% url 'register' %}" method="POST" class="form auth__form">
      {% csrf_token %}

        {% for field in form %}

        <div class="form__field">
          <label for="formInput#text">{{field.label}}: </label>
          {{field}}
        </div>

        {% endfor %}

      <div class="auth__actions">
        <input class="btn btn--sub btn--lg" type="submit" value="Sign  In" />
      </div>
    </form>
    <div class="auth__alternative">
      <p>Already have an Account?</p>
      <a href="{% url 'login' %}">Log In</a>
    </div>
  </div>
</div>

{% else %}

    <div class="auth">
        <div class="card">
          <div class="auth__header text-center">
            <a href="/">
              <img src="{% static 'images/icon.svg' %}" alt="icon" />
            </a>
            <h3>Account Login</h3>
            <p>Hello Developer, Welcome Back!</p>
          </div>
  
          <form action="" method="POST" class="form auth__form">
              {% csrf_token %}
            <!-- Input:Email -->
            <div class="form__field">
              <label for="formInput#text">Username: </label>
              <input
                class="input input--text"
                id="formInput#text"
                type="text"
                name="username"
                placeholder="Enter your username..."
              />
            </div>
  
            <!-- Input:Password -->
            <div class="form__field">
              <label for="formInput#password">Password: </label>
              <input
                class="input input--password"
                id="formInput#passowrd"
                type="password"
                name="password"
                placeholder="••••••••"
              />
            </div>
            <div class="auth__actions">
              <input class="btn btn--sub btn--lg" type="submit" value="Log In" />
              <a href="{% url 'reset_password' %}">Forget Password?</a>
            </div>
          </form>
          <div class="auth__alternative">
            <p>Don’t have an Account?</p>
            <a href="{% url 'register' %}">Sign Up</a>
          </div>
        </div>
      </div>

{% endif %}
{% endblock  %}

users/templates/users/message.html
{% extends 'main.html' %}
{% block content %}

<main class="messagePage my-xl">
    <div class="content-box">
      <div class="message">
        <a class="backButton" href="{% url 'inbox'  %}"><i class="im im-angle-left"></i></a>
        <h2 class="message__subject">{{unreadMsg.subject}}</h4>
            {% if unreadMsg.sender %}
          <a href="{% url 'user-profile' unreadMsg.sender.id %}" class="message__author">{{unreadMsg.name.title}}</a>
          {% else %}
          <p>note {{unreadMsg.name.title}} is not a user</p>
          <a class="message__author">{{unreadMsg.name.title}}</a>
          {% endif %}
          <p class="message__date">{{unreadMsg.created}}</p>
          <div class="message__body">
            {{unreadMsg.body}}
          </div>
      </div>
    </div>
  </main>
{% endblock %}

users/templates/users/message_form.html
{% extends 'main.html' %}
{% block content %}
<main class="formPage my-xl">
    <div class="content-box">
        <div class="formWrapper">
            <a class="backButton" href="{% url 'user-profile' recipient.id %}"><i class="im im-angle-left"></i></a>
            <br>

            <form class="form" action="" method="POST">
                {% csrf_token %}

                {% if request.user.is_authenticated == False %}
                <div class="form__field">
                    <label for="formInput#text">{{form.name.label}}: </label>
                    {{form.name}}
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{form.email.label}}: </label>
                    {{form.email}}
                </div>

                {% endif %}
                <!-- Input:Text -->
                <div class="form__field">
                    <label for="formInput#text">{{form.subject.label}}: </label>
                    {{form.subject}}
                </div>
                <div class="form__field">
                    <label for="formInput#text">{{form.body.label}}: </label>
                    {{form.body}}
                </div>

                
                <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
            </form>
        </div>
    </div>
</main>
{% endblock %}

users/templates/users/profile_form.html
{% extends 'main.html' %}

{% block content %}

    <main class="formPage my-xl">
        <div class="content-box">
            <div class="formWrapper">
                <a class="backButton" href="{% url 'account' %}"><i class="im im-angle-left"></i></a>
                <br>

                <form class="form" action="{% url 'edit-account' %}" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for field in form %}
                    <!-- Input:Text -->
                    <div class="form__field">
                        <label for="formInput#text">{{field.label}}: </label>
                        {{field}}
                    </div>
                    {% endfor %}

                    <input class="btn btn--sub btn--lg  my-md" type="submit" value="Submit" />
                </form>
            </div>
        </div>
    </main>

{% endblock %}

users/templates/users/user-profile.html
{% extends 'main.html' %}

{% block content %}
 <!-- Main Section -->
 <main class="profile my-md">
    <div class="container">
      <div class="layout">
        <div class="column column--1of3">
          <div class="card text-center">
            <div class="card__body dev">
              <img class="avatar avatar--xl" src="{{profile.profile_image.url}}" />
              <h2 class="dev__name">{{profile.name}}</h2>
              <p class="dev__title">{{profile.short_intro}}</p>
              <p class="dev__location">Based in {{profile.location}}</p>
              <ul class="dev__social">
                  {% if profile.social_github %}
                <li>
                  <a title="Github" href="{{ profile.social_github }}" target="_blank"><i class="im im-github"></i></a>
                </li>
                {% endif %}
                {% if profile.social_twitter %}
                
                <li>
                  <a title="Twitter" href="{{profile.social_twitter}}" target="_blank"><i class="im im-twitter"></i></a>
                </li>
                {% endif %}
                {% if profile.social_linkedin %}
                <li>
                  <a title="LinkedIn" href="{{ profile.social_linkedin }}" target="_blank"><i class="im im-linkedin"></i></a>
                </li>
                {% endif %}
                {% if profile.social_website %}
                <li>
                  <a title="Personal Website" href="{{profile.social_website}}" target="_blank"><i class="im im-globe"></i></a>
                </li>
                {% endif %}
              </ul>
              
              <a href="{% url 'create-message' profile.id %}" class="btn btn--sub btn--lg">Send Message </a>
              
            </div>
          </div>
        </div>
        <div class="column column--2of3">
          <div class="devInfo">
            <h3 class="devInfo__title">About Me</h3>
            <p class="devInfo__about">
             {{profile.bio}}
            </p>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Skills</h3>
            <div class="devInfo__skills">
            {% for skill in topSkills %}
                <div class="devSkill">
                    <h4 class="devSkill__title">{{skill.name}}</h4>
                    <p class="devSkill__info">
                    {{skill.description}}
                    </p>
                </div>
              {% endfor %}
              

              <h3 class="devInfo__subtitle">Other Skills</h3>
              <div class="devInfo__otherSkills">
                {% for skill in otherSkills %}
                        <span class="tag tag--pill tag--sub tag--lg">
                        <small>{{skill.name}}</small>
                </span>
                {% endfor %}
               
              </div>
            </div>
          </div>
          <div class="devInfo">
            <h3 class="devInfo__title">Projects</h3>
            <div class="grid grid--two">

              {% for project in profile.project_set.all %}
              <div class="column">
                <div class="card project">
                  <a href="{% url 'project' project.id %}" class="project">
                    <img class="project__thumbnail" src="{{project.featured_image.url}}" alt="project thumbnail" />
                    <div class="card__body">
                      <h3 class="project__title">{{project.title}}</h3>
                      <p><a class="project__author" href="{% url 'user-profile' project.owner.id %}">By {{project.owner.name}}</a></p>
                      <p class="project--rating">
                        <span style="font-weight: bold;">{{project.vote_ratio}}%</span> Postitive
                        Feedback ({{project.vote_total}} Vote{{project.vote_total | pluralize:'s'}})
                      </p>
                      <div class="project__tags">
                          {% for tag in project.tags.all %}
                        <span class="tag tag--pill tag--main">
                          <small>{{tag}}</small>
                        </span>
                       {% endfor %}
                      </div>
                    </div>
                  </a>
                </div>
              </div>
             {% endfor %}

            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
{% endblock %}